### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'glove/glove.6B.50d.txt'

### ISSUE THREAD

**Issue by FKCHAN** [Rokeer/co-attention#2]
FileNotFoundError: [Errno 2] No such file or directory: 'glove/glove.6B.50d.txt'

**Comment by rahuls321** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'glove/glove.6B.50d.txt'

Follow this link and download the glove 
https://nlp.stanford.edu/projects/glove
@FKCHAN

**Comment by Rokeer** [comment]
Thanks! @rahuls321
